export const LEGENDS = [
  {
    key: "facil",
    name: "Nara del Alba",
    epithet: "La Exploradora",
    difficulty: "Muy fácil",
    level: 1,
    rating: 450,
    sigil: "N",
    accent: "#72d7a7",
    description: "Juega sin prisa y deja oportunidades claras para aprender el tablero.",
    ai: { depth: 0, candidatePool: 99, nodeBudget: 150, thinkTimeMs: 240 },
  },
  {
    key: "novato",
    name: "Milo de la Brisa",
    epithet: "El Caminante",
    difficulty: "Fácil",
    level: 2,
    rating: 550,
    sigil: "M",
    accent: "#78d493",
    description: "Reconoce capturas sencillas, aunque todavía regala posiciones favorables.",
    ai: { depth: 0, candidatePool: 12, nodeBudget: 250, thinkTimeMs: 260 },
  },
  {
    key: "aprendiz",
    name: "Tomás del Roble",
    epithet: "El Guardián",
    difficulty: "Principiante",
    level: 3,
    rating: 675,
    sigil: "T",
    accent: "#8fca77",
    description: "Protege sus fichas y reconoce las capturas más evidentes.",
    ai: { depth: 0, candidatePool: 8, nodeBudget: 350, thinkTimeMs: 280 },
  },
  {
    key: "formativo",
    name: "Lía Paso Ligero",
    epithet: "La Discípula",
    difficulty: "Formación",
    level: 4,
    rating: 800,
    sigil: "L",
    accent: "#9bc86e",
    description: "Empieza a cuidar el centro y evita repetir errores demasiado obvios.",
    ai: { depth: 1, candidatePool: 8, nodeBudget: 500, thinkTimeMs: 300 },
  },
  {
    key: "astuto",
    name: "Bruno de Cobre",
    epithet: "El Oportunista",
    difficulty: "Astuto",
    level: 5,
    rating: 925,
    sigil: "B",
    accent: "#a9c56c",
    description: "Busca pequeños descuidos y comienza a preparar intercambios útiles.",
    ai: { depth: 1, candidatePool: 6, nodeBudget: 750, thinkTimeMs: 320 },
  },
  {
    key: "normal",
    name: "Amara del Río",
    epithet: "La Calculadora",
    difficulty: "Normal",
    level: 6,
    rating: 1050,
    sigil: "A",
    accent: "#63bfc2",
    description: "Valora material, avance y control del centro antes de actuar.",
    ai: { depth: 1, candidatePool: 5, nodeBudget: 1_100, thinkTimeMs: 340 },
  },
  {
    key: "intermedio",
    name: "Iker de la Niebla",
    epithet: "El Observador",
    difficulty: "Intermedio",
    level: 7,
    rating: 1175,
    sigil: "I",
    accent: "#5fbacb",
    description: "Detecta amenazas cercanas y rara vez abandona una ficha sin motivo.",
    ai: { depth: 1, candidatePool: 4, nodeBudget: 1_600, thinkTimeMs: 360 },
  },
  {
    key: "calculador",
    name: "Zahra Ojo Firme",
    epithet: "La Analista",
    difficulty: "Calculador",
    level: 8,
    rating: 1300,
    sigil: "Z",
    accent: "#61afd5",
    description: "Compara varias respuestas y presiona las diagonales más importantes.",
    ai: { depth: 2, candidatePool: 4, nodeBudget: 2_200, thinkTimeMs: 380 },
  },
  {
    key: "competente",
    name: "Darío Centinela",
    epithet: "El Táctico",
    difficulty: "Competente",
    level: 9,
    rating: 1425,
    sigil: "D",
    accent: "#6fa6dd",
    description: "Anticipa respuestas y castiga fichas expuestas en combinaciones cortas.",
    ai: { depth: 2, candidatePool: 3, nodeBudget: 3_200, thinkTimeMs: 410 },
  },
  {
    key: "tactico",
    name: "Kael Dos Filos",
    epithet: "El Cazador",
    difficulty: "Táctico",
    level: 10,
    rating: 1550,
    sigil: "K",
    accent: "#788fdf",
    description: "Tiende trampas de captura y obliga a elegir entre pérdidas difíciles.",
    ai: { depth: 2, candidatePool: 2, nodeBudget: 4_500, thinkTimeMs: 440 },
  },
  {
    key: "estratega",
    name: "Mireya del Laberinto",
    epithet: "La Arquitecta",
    difficulty: "Estratégico",
    level: 11,
    rating: 1675,
    sigil: "Y",
    accent: "#8587df",
    description: "Construye posiciones incómodas y limita tus rutas antes de atacar.",
    ai: { depth: 2, candidatePool: 2, nodeBudget: 6_500, thinkTimeMs: 470 },
  },
  {
    key: "avanzado",
    name: "Selene de Hierro",
    epithet: "La Estratega",
    difficulty: "Avanzado",
    level: 12,
    rating: 1800,
    sigil: "S",
    accent: "#9b8bdf",
    description: "Construye posiciones sólidas y rara vez concede una ventaja sencilla.",
    ai: { depth: 3, candidatePool: 2, nodeBudget: 9_500, thinkTimeMs: 500 },
  },
  {
    key: "maestromenor",
    name: "Orfeo Torre Gris",
    epithet: "El Instructor",
    difficulty: "Maestro",
    level: 13,
    rating: 1925,
    sigil: "O",
    accent: "#a57fdc",
    description: "Conserva ventajas pequeñas y transforma cada tempo en presión.",
    ai: { depth: 3, candidatePool: 2, nodeBudget: 13_500, thinkTimeMs: 530 },
  },
  {
    key: "granmaestro",
    name: "Isadora del Eclipse",
    epithet: "La Regente",
    difficulty: "Maestro Superior",
    level: 14,
    rating: 2050,
    sigil: "E",
    accent: "#b67bd6",
    description: "Calcula sin azar y convierte las debilidades estructurales en ataques.",
    ai: { depth: 3, candidatePool: 1, nodeBudget: 19_000, thinkTimeMs: 560 },
  },
  {
    key: "veterano",
    name: "Gael del Norte",
    epithet: "El Veterano",
    difficulty: "Veterano",
    level: 15,
    rating: 2175,
    sigil: "G",
    accent: "#c383d2",
    description: "Lee secuencias profundas y domina los cambios de ritmo.",
    ai: { depth: 4, candidatePool: 1, nodeBudget: 28_000, thinkTimeMs: 590 },
  },
  {
    key: "implacable",
    name: "Helena Implacable",
    epithet: "La Verdugo",
    difficulty: "Implacable",
    level: 16,
    rating: 2300,
    sigil: "H",
    accent: "#cf7bc0",
    description: "No desperdicia material y castiga casi todos los errores tácticos.",
    ai: { depth: 4, candidatePool: 1, nodeBudget: 40_000, thinkTimeMs: 620 },
  },
  {
    key: "elite",
    name: "Baltasar del Abismo",
    epithet: "El Insondable",
    difficulty: "Élite",
    level: 17,
    rating: 2425,
    sigil: "Ω",
    accent: "#d778a9",
    description: "Ve combinaciones largas y te obliga a defender desde el primer descuido.",
    ai: { depth: 5, candidatePool: 1, nodeBudget: 58_000, thinkTimeMs: 650 },
  },
  {
    key: "experto",
    name: "Valeria Implacable",
    epithet: "La Gran Maestra",
    difficulty: "Gran Maestro",
    level: 18,
    rating: 2550,
    sigil: "V",
    accent: "#de7d8d",
    description: "Calcula variantes extensas y convierte casi cualquier error en derrota.",
    ai: { depth: 5, candidatePool: 1, nodeBudget: 80_000, thinkTimeMs: 690 },
  },
  {
    key: "supremo",
    name: "Octavio Sin Error",
    epithet: "El Oráculo",
    difficulty: "Supremo",
    level: 19,
    rating: 2700,
    sigil: "∞",
    accent: "#e18a71",
    description: "Explora posiciones muy profundas y concede poquísimas oportunidades.",
    ai: { depth: 6, candidatePool: 1, nodeBudget: 110_000, thinkTimeMs: 730 },
  },
  {
    key: "maestro",
    name: "Aureliano Corona Eterna",
    epithet: "El Soberano",
    difficulty: "Casi imposible",
    level: 20,
    rating: 2900,
    sigil: "♛",
    accent: "#e8b85a",
    description: "La prueba final: máxima profundidad, precisión y cálculo sin concesiones.",
    ai: { depth: 7, candidatePool: 1, nodeBudget: 150_000, thinkTimeMs: 780 },
  },
] as const;

export type Legend = (typeof LEGENDS)[number];
export type LegendDifficultyKey = Legend["key"];

export function legendByKey(key: string): Legend | null {
  return LEGENDS.find((legend) => legend.key === key) || null;
}

export function legendIndex(key: LegendDifficultyKey): number {
  return LEGENDS.findIndex((legend) => legend.key === key);
}
