export const LEGENDS = [
  {
    key: "facil",
    name: "Kóbalos",
    epithet: "El Embaucador",
    difficulty: "Muy fácil",
    level: 1,
    rating: 600,
    sigil: "K",
    portrait: "/assets/characters/facil.avif",
    accent: "#72d7a7",
    description: "Un espíritu travieso pero inofensivo que deja oportunidades claras para aprender.",
    ai: { depth: 0, candidatePool: 99, nodeBudget: 150, thinkTimeMs: 240 },
  },
  {
    key: "aprendiz",
    name: "Circe",
    epithet: "La Hechicera",
    difficulty: "Fácil",
    level: 2,
    rating: 725,
    sigil: "C",
    portrait: "/assets/characters/aprendiz.avif",
    accent: "#78d493",
    description: "Conoce las tácticas básicas, pero todavía comete errores que puedes aprovechar.",
    ai: { depth: 0, candidatePool: 12, nodeBudget: 250, thinkTimeMs: 260 },
  },
  {
    key: "normal",
    name: "Crocotta",
    epithet: "La Voz Salvaje",
    difficulty: "Principiante",
    level: 3,
    rating: 855,
    sigil: "C",
    portrait: "/assets/characters/normal.avif",
    accent: "#8fca77",
    description: "Una bestia mimética que reconoce capturas y calcula sus primeras respuestas.",
    ai: { depth: 0, candidatePool: 8, nodeBudget: 350, thinkTimeMs: 280 },
  },
  {
    key: "competente",
    name: "Duende",
    epithet: "El Astuto",
    difficulty: "Formativo",
    level: 4,
    rating: 980,
    sigil: "D",
    portrait: "/assets/characters/competente.avif",
    accent: "#9bc86e",
    description: "Juega con astucia, cuida el centro y empieza a castigar los descuidos evidentes.",
    ai: { depth: 1, candidatePool: 8, nodeBudget: 500, thinkTimeMs: 300 },
  },
  {
    key: "avanzado",
    name: "Anteo",
    epithet: "Hijo de la Tierra",
    difficulty: "Normal",
    level: 5,
    rating: 1_105,
    sigil: "A",
    portrait: "/assets/characters/avanzado.avif",
    accent: "#a9c56c",
    description: "Un luchador resistente que prepara intercambios y rara vez abandona una ficha.",
    ai: { depth: 1, candidatePool: 6, nodeBudget: 750, thinkTimeMs: 320 },
  },
  {
    key: "veterano",
    name: "Einherjar",
    epithet: "El Guerrero Eterno",
    difficulty: "Intermedio",
    level: 6,
    rating: 1_230,
    sigil: "E",
    portrait: "/assets/characters/veterano.avif",
    accent: "#63bfc2",
    description: "Un guerrero experimentado al que rara vez se le escapa una captura.",
    ai: { depth: 1, candidatePool: 5, nodeBudget: 1_100, thinkTimeMs: 340 },
  },
  {
    key: "experto",
    name: "Asmodeo",
    epithet: "El Demonio del Cálculo",
    difficulty: "Competente",
    level: 7,
    rating: 1_360,
    sigil: "A",
    portrait: "/assets/characters/experto.avif",
    accent: "#5fbacb",
    description: "Analiza la posición con paciencia y detecta amenazas antes de que aparezcan.",
    ai: { depth: 1, candidatePool: 4, nodeBudget: 1_600, thinkTimeMs: 360 },
  },
  {
    key: "maestro",
    name: "Licaón",
    epithet: "El Cazador",
    difficulty: "Avanzado",
    level: 8,
    rating: 1_485,
    sigil: "L",
    portrait: "/assets/characters/maestro.avif",
    accent: "#61afd5",
    description: "Calcula con precisión de cazador y ofrece pocos errores para aprovechar.",
    ai: { depth: 2, candidatePool: 4, nodeBudget: 2_200, thinkTimeMs: 380 },
  },
  {
    key: "imposible",
    name: "Grendel",
    epithet: "El Devorador",
    difficulty: "Experto",
    level: 9,
    rating: 1_610,
    sigil: "G",
    portrait: "/assets/characters/imposible.avif",
    accent: "#6fa6dd",
    description: "Un monstruo táctico que anticipa respuestas y castiga las fichas expuestas.",
    ai: { depth: 2, candidatePool: 3, nodeBudget: 3_200, thinkTimeMs: 410 },
  },
  {
    key: "sobrehumano",
    name: "Jötunn",
    epithet: "El Gigante",
    difficulty: "Maestro",
    level: 10,
    rating: 1_735,
    sigil: "J",
    portrait: "/assets/characters/sobrehumano.avif",
    accent: "#788fdf",
    description: "Un gigante que prepara trampas de captura y casi nunca pierde material gratis.",
    ai: { depth: 2, candidatePool: 2, nodeBudget: 4_500, thinkTimeMs: 440 },
  },
  {
    key: "implacable",
    name: "Wendigo",
    epithet: "El Hambre Infinita",
    difficulty: "Implacable",
    level: 11,
    rating: 1_865,
    sigil: "W",
    portrait: "/assets/characters/implacable.avif",
    accent: "#8587df",
    description: "Un hambre insaciable que presiona sin pausa y no perdona descuidos tácticos.",
    ai: { depth: 2, candidatePool: 2, nodeBudget: 6_500, thinkTimeMs: 470 },
  },
  {
    key: "titan",
    name: "Fenrir",
    epithet: "El Lobo Encadenado",
    difficulty: "Titán",
    level: 12,
    rating: 1_990,
    sigil: "F",
    portrait: "/assets/characters/titan.avif",
    accent: "#9b8bdf",
    description: "El gran lobo domina el tablero con fuerza y construye posiciones muy sólidas.",
    ai: { depth: 3, candidatePool: 2, nodeBudget: 9_500, thinkTimeMs: 500 },
  },
  {
    key: "mitico",
    name: "Ammit",
    epithet: "La Devoradora",
    difficulty: "Mítico",
    level: 13,
    rating: 2_115,
    sigil: "A",
    portrait: "/assets/characters/mitico.avif",
    accent: "#a57fdc",
    description: "La devoradora de los muertos conserva cada ventaja y aumenta la presión.",
    ai: { depth: 3, candidatePool: 2, nodeBudget: 13_500, thinkTimeMs: 530 },
  },
  {
    key: "legendario",
    name: "Draugr",
    epithet: "El Guerrero Muerto",
    difficulty: "Legendario",
    level: 14,
    rating: 2_240,
    sigil: "D",
    portrait: "/assets/characters/legendario.avif",
    accent: "#b67bd6",
    description: "Un guerrero muerto viviente que calcula sin azar y convierte cada debilidad.",
    ai: { depth: 3, candidatePool: 1, nodeBudget: 19_000, thinkTimeMs: 560 },
  },
  {
    key: "trascendental",
    name: "Vetala",
    epithet: "El Espíritu Errante",
    difficulty: "Trascendental",
    level: 15,
    rating: 2_370,
    sigil: "V",
    portrait: "/assets/characters/trascendental.avif",
    accent: "#c383d2",
    description: "Un espíritu que anticipa combinaciones profundas que otros no alcanzan a ver.",
    ai: { depth: 4, candidatePool: 1, nodeBudget: 28_000, thinkTimeMs: 590 },
  },
  {
    key: "sobrenatural",
    name: "Upiór",
    epithet: "El No Muerto",
    difficulty: "Sobrenatural",
    level: 16,
    rating: 2_495,
    sigil: "U",
    portrait: "/assets/characters/sobrenatural.avif",
    accent: "#cf7bc0",
    description: "Juega como si conociera el futuro y castiga casi todos los errores tácticos.",
    ai: { depth: 4, candidatePool: 1, nodeBudget: 40_000, thinkTimeMs: 620 },
  },
  {
    key: "insuperable",
    name: "Strigoi",
    epithet: "El Inmortal",
    difficulty: "Insuperable",
    level: 17,
    rating: 2_620,
    sigil: "S",
    portrait: "/assets/characters/insuperable.avif",
    accent: "#d778a9",
    description: "Un espíritu inmortal que ve combinaciones largas desde el primer descuido.",
    ai: { depth: 5, candidatePool: 1, nodeBudget: 58_000, thinkTimeMs: 650 },
  },
  {
    key: "divino",
    name: "Moloc",
    epithet: "La Deidad Oscura",
    difficulty: "Divino",
    level: 18,
    rating: 2_745,
    sigil: "M",
    portrait: "/assets/characters/divino.avif",
    accent: "#de7d8d",
    description: "Una deidad de precisión casi absoluta que convierte cualquier error en derrota.",
    ai: { depth: 5, candidatePool: 1, nodeBudget: 80_000, thinkTimeMs: 690 },
  },
  {
    key: "absoluto",
    name: "Sobek",
    epithet: "El Dios Cocodrilo",
    difficulty: "Absoluto",
    level: 19,
    rating: 2_875,
    sigil: "S",
    portrait: "/assets/characters/absoluto.avif",
    accent: "#e18a71",
    description: "No deja margen de error y explora cada posición con profundidad extraordinaria.",
    ai: { depth: 6, candidatePool: 1, nodeBudget: 110_000, thinkTimeMs: 730 },
  },
  {
    key: "coronaeterna",
    name: "Hades",
    epithet: "Señor del Inframundo",
    difficulty: "Casi imposible",
    level: 20,
    rating: 3_000,
    sigil: "♛",
    portrait: "/assets/characters/coronaeterna.avif",
    accent: "#e8b85a",
    description: "El dueño del trono eterno: máxima profundidad, precisión y cálculo sin concesiones.",
    ai: { depth: 7, candidatePool: 1, nodeBudget: 150_000, thinkTimeMs: 780 },
  },
  {
    key: "behemoth",
    name: "Behemoth",
    epithet: "El Coloso Elemental",
    difficulty: "Imposible",
    level: 21,
    rating: 3_125,
    sigil: "B",
    portrait: "/assets/characters/behemoth.avif",
    accent: "#d9634f",
    description: "Un coloso elemental que no conoce la fatiga y presiona cada línea sin fisuras.",
    ai: { depth: 7, candidatePool: 1, nodeBudget: 195_000, thinkTimeMs: 825 },
  },
  {
    key: "gogmagog",
    name: "Gogmagog",
    epithet: "El Último Gigante",
    difficulty: "Imposible",
    level: 22,
    rating: 3_250,
    sigil: "G",
    portrait: "/assets/characters/gogmagog.avif",
    accent: "#c94f3f",
    description: "El último de los gigantes primordiales: fuerza bruta y cálculo que no dejan escapatoria.",
    ai: { depth: 8, candidatePool: 1, nodeBudget: 245_000, thinkTimeMs: 870 },
  },
  {
    key: "amarok",
    name: "Amarok",
    epithet: "El Lobo del Ártico",
    difficulty: "Imposible",
    level: 23,
    rating: 3_375,
    sigil: "A",
    portrait: "/assets/characters/amarok.avif",
    accent: "#b83f4a",
    description: "Un lobo colosal que acecha en silencio y cierra cualquier posición en su favor.",
    ai: { depth: 8, candidatePool: 1, nodeBudget: 300_000, thinkTimeMs: 915 },
  },
  {
    key: "charon",
    name: "Caronte",
    epithet: "El Barquero de las Almas",
    difficulty: "Muy imposible",
    level: 24,
    rating: 3_500,
    sigil: "C",
    portrait: "/assets/characters/charon.avif",
    accent: "#8f3350",
    description: "El barquero de las almas cobra cada error con precisión inapelable.",
    ai: { depth: 8, candidatePool: 1, nodeBudget: 360_000, thinkTimeMs: 960 },
  },
  {
    key: "thanatos",
    name: "Thanatos",
    epithet: "La Muerte Misma",
    difficulty: "Muy imposible",
    level: 25,
    rating: 3_625,
    sigil: "☠",
    portrait: "/assets/characters/thanatos.avif",
    accent: "#5a2340",
    description: "La muerte misma: no comete errores, no se apresura y no perdona ni una sola ficha.",
    ai: { depth: 8, candidatePool: 1, nodeBudget: 425_000, thinkTimeMs: 1_005 },
  },
] as const;

export type Legend = (typeof LEGENDS)[number];
export type LegendDifficultyKey = Legend["key"];

export function legendByKey(key: string): Legend | null {
  return LEGENDS.find((legend) => legend.key === key) || null;
}

export function legendIndex(key: LegendDifficultyKey): number {
  return LEGENDS.findIndex((legend) => legend.key === key);
}
